
#Electric Motor
[electric_motor]
	#Electric Motor minimum RPM.
	#Range: 0 ~ 256
	motor_min_rpm = 8
	#Electric Motor maximum RPM.
	#Range: 1 ~ 256
	motor_max_rpm = 256
	#Electric Motor max input in FE.
	#Range: 0 ~ 32767
	motor_max_input = 8192
	#Electric Motor internal capacity in FE.
	#Range: 0 ~ 32767
	motor_capacity = 16000
	#Electric Motor consumption in FE/t at max RPM.
	#Range: 0 ~ 32767
	motor_consumption = 60
	#Electric Motor generated base stress (Not implemented).
	#Range: 0 ~ 256
	motor_stress = 16

#Alternator
[alternator]
	#Alternator max input in FE.
	#Range: 0 ~ 32767
	generator_max_output = 32768
	#Alternator internal capacity in FE.
	#Range: 0 ~ 32767
	generator_capacity = 320000
	#Alternator base stress impact.
	#Range: 0 ~ 1024
	generator_consumption = 16

#Rolling Mill
[rolling_mill]
	#Rolling Mill duration in ticks.
	#Range: 0 ~ 32767
	rolling_mill_processing_duration = 100
	#Rolling Mill base stress impact.
	#Range: 0 ~ 1024
	rolling_mill_stress = 16

